### PR TITLE
[WIP] Sovrin and Node GHA CD

### PR DESCRIPTION
**Pull request by askolesov**

### CODE REVIEW

**Comment by WadeBarnes** [comment]
@askolesov, DCO sign-off needs to be fixed.

**Comment by askolesov** [comment]
@WadeBarnes Sorry, It's another dead PR. Better to close in order not to confuse people.

**Comment by devinleighsmith** [comment]
@askolesov since you were working on this, were you able to get these tests to pass? noticing that you've fixed a lot of the issues that I've run into today, such as needing to pin pip in the client to <10. 

If so, what dependency versions worked for you, if you still have that information?

**Comment by devinleighsmith** [comment]
oh interesting, looks like this PR corresponds to a PR within sovrin for a GHA, which appears to include all of the env vars that you were using with run.sh 

will give that a go.

**Comment by askolesov** [comment]
@devinleighsmith Hi, better look here:
https://github.com/hyperledger/indy-node/pull/1662/files

I started with Sovrin but switched to Node, was able to run some system tests, and then was pulled to another project.

**Comment by devinleighsmith** [comment]
@askolesov thanks for this.

**Pull request closed without merging**
